# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20160517_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
