# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
