# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20160519_1218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='share_userprofile',
        ),
    ]
