# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20160519_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='types',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head',
            field=models.ImageField(blank=True, default='static/user.jpg', upload_to='static'),
        ),
        migrations.DeleteModel(
            name='Ebook',
        ),
    ]
