# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 01:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0007_auto_20160521_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('brief', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('pub_at', models.CharField(max_length=15)),
                ('references', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Type')),
            ],
        ),
    ]
