# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20160521_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_manage', 'Can Manage comments'),)},
        ),
    ]
