# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_auto_20160524_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.BooleanField(default=False),
        ),
    ]
