# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Ebook')),
            ],
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
