# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20160507_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
