# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20160507_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='type',
            name='ebook',
        ),
    ]
