# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20160507_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
