# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20160507_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=2000)),
                ('realname', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
