# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20160508_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headimg',
            field=models.FileField(blank=True, upload_to='./upload'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
