# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20160508_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, upload_to='../upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='headimg',
        ),
    ]
